import { FinancialCategory } from "../../types";

export const DEFAULT_FINANCIAL_CATEGORIES: Omit<FinancialCategory, "id" | "companyId" | "createdAt">[] = [
  // 1. Locações — Entradas (natureza: entrada, grupo: locacao, comportamento: nao_aplicavel, origem: locacao)
  {
    name: "Aluguel Recebido",
    nome: "Aluguel Recebido",
    type: "RECEITA",
    natureza: "entrada",
    group: "Locações",
    grupo: "locacao",
    comportamento: "nao_aplicavel",
    origem: "locacao",
    color: "#059669",
    icon: "Tag",
    isDefault: true
  },
  {
    name: "Taxa de Administração",
    nome: "Taxa de Administração",
    type: "RECEITA",
    natureza: "entrada",
    group: "Locações",
    grupo: "locacao",
    comportamento: "nao_aplicavel",
    origem: "locacao",
    color: "#0d9488",
    icon: "Tag",
    isDefault: true
  },
  {
    name: "Primeiro Aluguel",
    nome: "Primeiro Aluguel",
    type: "RECEITA",
    natureza: "entrada",
    group: "Locações",
    grupo: "locacao",
    comportamento: "nao_aplicavel",
    origem: "locacao",
    color: "#0f766e",
    icon: "Tag",
    isDefault: true
  },

  // 2. Locações — Saídas (natureza: saida, grupo: locacao, comportamento: nao_aplicavel, origem: locacao)
  {
    name: "Repasse Proprietário",
    nome: "Repasse Proprietário",
    type: "DESPESA",
    natureza: "saida",
    group: "Locações",
    grupo: "locacao",
    comportamento: "nao_aplicavel",
    origem: "locacao",
    color: "#e11d48",
    icon: "Tag",
    isDefault: true
  },
  {
    name: "Repasse Corretor",
    nome: "Repasse Corretor",
    type: "DESPESA",
    natureza: "saida",
    group: "Locações",
    grupo: "locacao",
    comportamento: "nao_aplicavel",
    origem: "locacao",
    color: "#dd2727",
    icon: "Tag",
    isDefault: true
  },

  // 3. Caixa — Entradas (natureza: entrada, grupo: caixa, comportamento: nao_aplicavel, origem: venda | administracao | outros)
  {
    name: "Comissão de Venda",
    nome: "Comissão de Venda",
    type: "RECEITA",
    natureza: "entrada",
    group: "Caixa",
    grupo: "caixa",
    comportamento: "nao_aplicavel",
    origem: "venda",
    color: "#2563eb",
    icon: "Tag",
    isDefault: true
  },
  {
    name: "Honorários",
    nome: "Honorários",
    type: "RECEITA",
    natureza: "entrada",
    group: "Caixa",
    grupo: "caixa",
    comportamento: "nao_aplicavel",
    origem: "administracao",
    color: "#4f46e5",
    icon: "Tag",
    isDefault: true
  },
  {
    name: "Outros Serviços",
    nome: "Outros Serviços",
    type: "RECEITA",
    natureza: "entrada",
    group: "Caixa",
    grupo: "caixa",
    comportamento: "nao_aplicavel",
    origem: "outros",
    color: "#0891b2",
    icon: "Tag",
    isDefault: true
  },

  // 4. Caixa — Saídas Fixas (natureza: saida, grupo: caixa, comportamento: fixo, origem: outros / etc)
  {
    name: "Aluguel Escritório",
    nome: "Aluguel Escritório",
    type: "DESPESA",
    natureza: "saida",
    group: "Caixa",
    grupo: "caixa",
    comportamento: "fixo",
    origem: "outros",
    color: "#475569",
    icon: "Tag",
    isDefault: true
  },
  {
    name: "Internet",
    nome: "Internet",
    type: "DESPESA",
    natureza: "saida",
    group: "Caixa",
    grupo: "caixa",
    comportamento: "fixo",
    origem: "outros",
    color: "#64748b",
    icon: "Tag",
    isDefault: true
  },
  {
    name: "Telefone",
    nome: "Telefone",
    type: "DESPESA",
    natureza: "saida",
    group: "Caixa",
    grupo: "caixa",
    comportamento: "fixo",
    origem: "outros",
    color: "#334155",
    icon: "Tag",
    isDefault: true
  },
  {
    name: "Energia",
    nome: "Energia",
    type: "DESPESA",
    natureza: "saida",
    group: "Caixa",
    grupo: "caixa",
    comportamento: "fixo",
    origem: "outros",
    color: "#1e293b",
    icon: "Tag",
    isDefault: true
  },
  {
    name: "Pró-labore",
    nome: "Pró-labore",
    type: "DESPESA",
    natureza: "saida",
    group: "Caixa",
    grupo: "caixa",
    comportamento: "fixo",
    origem: "outros",
    color: "#0f172a",
    icon: "Tag",
    isDefault: true
  },
  {
    name: "Salários",
    nome: "Salários",
    type: "DESPESA",
    natureza: "saida",
    group: "Caixa",
    grupo: "caixa",
    comportamento: "fixo",
    origem: "outros",
    color: "#57534e",
    icon: "Tag",
    isDefault: true
  },
  {
    name: "Imobilead",
    nome: "Imobilead",
    type: "DESPESA",
    natureza: "saida",
    group: "Caixa",
    grupo: "caixa",
    comportamento: "fixo",
    origem: "outros",
    color: "#44403c",
    icon: "Tag",
    isDefault: true
  },
  {
    name: "Contador",
    nome: "Contador",
    type: "DESPESA",
    natureza: "saida",
    group: "Caixa",
    grupo: "caixa",
    comportamento: "fixo",
    origem: "outros",
    color: "#78716c",
    icon: "Tag",
    isDefault: true
  },
  {
    name: "Assinaturas",
    nome: "Assinaturas",
    type: "DESPESA",
    natureza: "saida",
    group: "Caixa",
    grupo: "caixa",
    comportamento: "fixo",
    origem: "outros",
    color: "#a8a29e",
    icon: "Tag",
    isDefault: true
  },

  // 5. Caixa — Saídas Variáveis (natureza: saida, grupo: caixa, comportamento: variavel, origem: outros / etc)
  {
    name: "Tráfego Pago",
    nome: "Tráfego Pago",
    type: "DESPESA",
    natureza: "saida",
    group: "Caixa",
    grupo: "caixa",
    comportamento: "variavel",
    origem: "outros",
    color: "#d97706",
    icon: "Tag",
    isDefault: true
  },
  {
    name: "Combustível",
    nome: "Combustível",
    type: "DESPESA",
    natureza: "saida",
    group: "Caixa",
    grupo: "caixa",
    comportamento: "variavel",
    origem: "outros",
    color: "#ca8a04",
    icon: "Tag",
    isDefault: true
  },
  {
    name: "Comissões Externas",
    nome: "Comissões Externas",
    type: "DESPESA",
    natureza: "saida",
    group: "Caixa",
    grupo: "caixa",
    comportamento: "variavel",
    origem: "venda",
    color: "#ea580c",
    icon: "Tag",
    isDefault: true
  },
  {
    name: "Brindes e Eventos",
    nome: "Brindes e Eventos",
    type: "DESPESA",
    natureza: "saida",
    group: "Caixa",
    grupo: "caixa",
    comportamento: "variavel",
    origem: "outros",
    color: "#db2777",
    icon: "Tag",
    isDefault: true
  },
  {
    name: "Material Gráfico",
    nome: "Material Gráfico",
    type: "DESPESA",
    natureza: "saida",
    group: "Caixa",
    grupo: "caixa",
    comportamento: "variavel",
    origem: "outros",
    color: "#c026d3",
    icon: "Tag",
    isDefault: true
  },
  {
    name: "Manutenções",
    nome: "Manutenções",
    type: "DESPESA",
    natureza: "saida",
    group: "Caixa",
    grupo: "caixa",
    comportamento: "variavel",
    origem: "outros",
    color: "#7c3aed",
    icon: "Tag",
    isDefault: true
  },
  {
    name: "Alimentação",
    nome: "Alimentação",
    type: "DESPESA",
    natureza: "saida",
    group: "Caixa",
    grupo: "caixa",
    comportamento: "variavel",
    origem: "outros",
    color: "#9333ea",
    icon: "Tag",
    isDefault: true
  },
  {
    name: "Adiantamento a Corretor (Recuperável)",
    nome: "Adiantamento a Corretor (Recuperável)",
    type: "DESPESA",
    natureza: "saida",
    group: "Caixa",
    grupo: "caixa",
    comportamento: "variavel",
    origem: "locacao",
    color: "#6366f1",
    icon: "Tag",
    isDefault: true,
    excludeFromDRE: true
  }
];
